### ISSUE TITLE
[Bug] Cannot save application settings after configuring server-side database

### ISSUE THREAD

**Issue by TigerBeanst** [lobehub/lobehub#3481]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.11.1(96c34790c174273d8ba37d3c60e0e36fe0c7d7a9)

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

配置了服务端数据库，登录环节正常，但无法保存/同步数据
已经尝试重新配置一遍 Cloudflare R2 的 Endpoints 地址和两个密钥

![image](https://github.com/user-attachments/assets/bdd6772a-1a1c-4ba6-aea8-219e2ee6d46c)
进行编辑的时候弹出报错，接口是：`/trpc/lambda/user.updateSettings?batch=1`
入参：
```json
{
  "0": {
    "json": {
      "defaultAgent": {},
      "general": {},
      "keyVaults": { "openai": { "apiKey": "121" } },
      "languageModel": {},
      "systemAgent": {},
      "tool": {},
      "tts": {}
    }
  }
}
```

返参：
```json
[
    {
        "error": {
            "json": {
                "message": "Invalid key length",
                "code": -32603,
                "data": {
                    "code": "INTERNAL_SERVER_ERROR",
                    "httpStatus": 500,
                    "path": "user.updateSettings"
                }
            }
        }
    }
]
```

Vercel 日志：
```
DataError: Invalid key length
    at new DOMException (node:internal/per_context/domexception:53:5)
    ... 8 lines matching cause stack trace ...
    at t (/var/task/.next/server/chunks/94376.js:1:2180) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: DOMException [DataError]: Invalid key length
      at new DOMException (node:internal/per_context/domexception:53:5)
      at __node_internal_ (node:internal/util:670:10)
      at validateKeyLength (node:internal/crypto/aes:77:11)
      at Object.aesImportKey (node:internal/crypto/aes:271:7)
      at SubtleCrypto.importKey (node:internal/crypto/webcrypto:641:10)
      at d.initWithEnvKey (/var/task/.next/server/chunks/9132.js:7:67)
      at f.updateSetting (/var/task/.next/server/chunks/9132.js:7:935)
      at /var/task/.next/server/app/trpc/lambda/[trpc]/route.js:6:4425
      at E.f.middlewares (/var/task/.next/server/chunks/94376.js:1:1906)
      at t (/var/task/.next/server/chunks/94376.js:1:2180)
}
```

Vercel 配置过的 环境变量：
- S3_SECRET_ACCESS_KEY
- S3_ACCESS_KEY_ID
- S3_ENDPOINT
- NEXT_PUBLIC_S3_DOMAIN
- S3_BUCKET
- CLERK_WEBHOOK_SECRET
- CLERK_SECRET_KEY
- NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
- KEY_VAULTS_SECRET
- NEXT_PUBLIC_SERVICE_MODE
- DATABASE_URL

**Comment by arvinxx** [comment]
感觉是你的加密 key 配的不对吧？你的 KEY_VAULT 的字段是咋配的？

**Comment by TigerBeanst** [comment]
> 感觉是你的加密 key 配的不对吧？你的 KEY_VAULT 的字段是咋配的？

`KEY_VAULTS_SECRET` 是用 Bitwarden 生成的一串带 `*` `!` `&` 特殊字符和大小写的密码，确认了是 32 位

**Comment by TigerBeanst** [comment]
🤣测试完了，可能是 `KEY_VAULTS_SECRET` 不支持那些特殊符号，我用 openssl 生成的没问题……
当时看文档没看到说有限制，只是说32个字符所以就用密码生成器生成了……

**Comment by youralmight** [comment]
我今天同样遇到了这个问题，希望能够更改文档，防止后面有人继续遇到这个问题

**Comment by youralmight** [comment]
@TigerBeanst 你要重新开一下issue吗，这个问题总不能一直持续下去吧

**Comment by arvinxx** [comment]
> 我今天同样遇到了这个问题，希望能够更改文档，防止后面有人继续遇到这个问题

@youralmight 你觉得要怎么改？欢迎来提 PR

**Comment by TigerBeanst** [comment]
> > 我今天同样遇到了这个问题，希望能够更改文档，防止后面有人继续遇到这个问题
> 
> @youralmight 你觉得要怎么改？欢迎来提 PR

我个人感觉其实只需要把原本类似于
> 您可以使用以下命令生成秘钥： openssl rand -base64 32

改成诸如
> 您需要使用以下命令生成秘钥： openssl rand -base64 32.

之类的就行？或者强调密钥的合法条件情况
原本的意思让我以为提供这个语句只是方便生成，密钥本身没有过多条件要求

**Comment by youralmight** [comment]
我和 @TigerBeanst 一样，使用密码生成器生成了一段32个字母的包含大小写字母和数字和随意特殊符号的字符串。
文档中样例字符串包含字符'/'和'='，这使我认为字符串中使用任何特殊符号都是合法的。所以，文档可以修改为显式地向读者说明合法的字符集为`A-Za-z0-9+/`。
