### ISSUE TITLE
[Bug] Docker-database depoly File Chunk Error

### ISSUE THREAD

**Issue by Lostsite** [lobehub/lobehub#3819]
### 📦 Environment

Docker

### 📌 Version

v1.15.18

### 💻 Operating System

Ubuntu, Other Linux

### 🌐 Browser

Firefox

### 🐛 Bug Description

Upload a file, try to chunk, filed. The file can correctly preview and download, just can't chunk.

Here is the error log (confidential information been removed, include domain name and token):
```
[ParseFileToChunks] error: d [TRPCClientError]: Unsupported GET-request to mutation procedure at path "file.parseFileToChunks"
    at d.from (/app/.next/server/chunks/35260.js:31:134869)
    at /app/.next/server/chunks/35260.js:31:140525
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: {
    response: Response {
      status: 405,
      statusText: 'Method Not Allowed',
      headers: Headers {
        date: 'Sun, 08 Sep 2024 05:07:41 GMT',
        server: 'Apache/2.4.62 (Debian)',
        vary: 'RSC,Next-Router-State-Tree,Next-Router-Prefetch,trpc-accept',
        'content-type': 'application/json',
        'set-cookie': '__Host-authjs.csrf-token=token_value_removed; Path=/; HttpOnly; Secure; SameSite=Lax, __Secure-authjs.callback-url=https%3A%2F%2Fmy.domain.example.com; Path=/; HttpOnly; Secure; SameSite=Lax',
        'keep-alive': 'timeout=5, max=100',
        connection: 'Keep-Alive',
        'transfer-encoding': 'chunked'
      },
      body: ReadableStream { locked: true, state: 'closed', supportsBYOB: true },
      bodyUsed: true,
      ok: false,
      redirected: true,
      type: 'cors',
      url: 'https://my.domain.example.com/trpc/async/file.parseFileToChunks?batch=1'
    },
    responseJSON: [ [Object] ]
  },
  shape: {
    message: 'Unsupported GET-request to mutation procedure at path "file.parseFileToChunks"',
    code: -32005,
    data: {
      code: 'METHOD_NOT_SUPPORTED',
      httpStatus: 405,
      path: 'file.parseFileToChunks'
    }
  },
  data: {
    code: 'METHOD_NOT_SUPPORTED',
    httpStatus: 405,
    path: 'file.parseFileToChunks'
  },
  [cause]: undefined
}
```

### 📷 Recurrence Steps

Special steps during deploy:
docker arguments:

`docker run -it -d -p 127.0.0.1:3210:3210 --network="host"  --------- (rest are same)`

(Set --network="host" to connect to local pgsql)

Set nft tables to drop all traffic from outside to port 3210

```
table ip filter {
    chain input {
        type filter hook input priority 0; policy accept;
        iifname != "lo" tcp dport 3210 counter drop
    }
}
```

Set Apache httpd to do reverse proxy

```
<VirtualHost *:80>
    ServerName my.domain.example.com

    ProxyPreserveHost On
    ProxyPass / http://localhost:3210/
    ProxyPassReverse / http://localhost:3210/

    ErrorLog ${APACHE_LOG_DIR}/my.domain.example.com.log
    CustomLog ${APACHE_LOG_DIR}/my.domain.example.com-access.log combined
</VirtualHost>
```

Last use certbot to get a CA, also let it auto config the https redirect.

### 📝 Additional Information

Server Operating System: Debian 12, with local pgsql installation.

**Comment by Lostsite** [comment]
If anyone can give me a hint? I just tried to deploy the newest docker image, the same issue happens once again. Still gives ``` message: 'Unsupported GET-request to mutation procedure at path "file.parseFileToChunks"'```

If anyone had successfully performed docker deploy with reverse proxy, could anyone give me a hint about how to correctly deploy this?
