### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by retaw106** [lobehub/lobehub#4580]
### 📦 部署环境

Docker

### 📌 软件版本

1.26.17

### 💻 系统环境

Windows, Android

### 🌐 浏览器

Firefox, Other

### 🐛 问题描述

在firefox浏览器或手机浏览器上无法使用语音输入，弹出提示框“很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试”。使用chrome浏览器则语音输入正常。
docker日志如下：
```
lobe-chat  |  ⨯ TypeError: terminated
lobe-chat  |     at _Fetch.onAborted (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:12205:53)
lobe-chat  |     at _Fetch.emit (node:events:519:28)
lobe-chat  |     at _Fetch.terminate (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:11393:14)
lobe-chat  |     at Object.onError (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:12310:38)
lobe-chat  |     at _Request2.onError (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:8942:31)
lobe-chat  |     at errorRequest (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:11060:17)
lobe-chat  |     at TLSSocket.onSocketClose (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:10477:9)
lobe-chat  |     at TLSSocket.emit (node:events:531:35)
lobe-chat  |     at node:net:339:12
lobe-chat  |     at TCP.done (node:_tls_wrap:648:7) {
lobe-chat  |   [cause]: SocketError: other side closed
lobe-chat  |       at TLSSocket.onSocketEnd (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:10455:26)
lobe-chat  |       at TLSSocket.emit (node:events:531:35)
lobe-chat  |       at endReadableNT (node:internal/streams/readable:1696:12)
lobe-chat  |       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
lobe-chat  |     code: 'UND_ERR_SOCKET',
lobe-chat  |     socket: {
lobe-chat  |       localAddress: '172.25.0.15',
lobe-chat  |       localPort: 52032,
lobe-chat  |       remoteAddress: '40.76.107.132',
lobe-chat  |       remotePort: 443,
lobe-chat  |       remoteFamily: 'IPv4',
lobe-chat  |       timeout: undefined,
lobe-chat  |       bytesWritten: 78856,
lobe-chat  |       bytesRead: 999
lobe-chat  |     }
lobe-chat  |   }
lobe-chat  | }
```

**Comment by retaw106** [comment]
我使用的是https网址，反向代理由nginx proxy manager搭建，NPM中已打开Websockets support
