### ISSUE TITLE
[Bug] Chunking failed NoChunkError

### ISSUE THREAD

**Issue by SystemDev01** [lobehub/lobehub#5046]
### 📦 部署环境

Docker

### 📌 软件版本

v1.36.25

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/3253f3e1-4892-4609-9334-d3bc5f146fd2)
![image](https://github.com/user-attachments/assets/904285f3-45cf-4ca3-b09c-1c7505109518)

查看浏览器F12，没有接口报错，日志报错如下
next auth: undefined
a [TRPCError]: UNAUTHORIZED
    at /app/.next/server/chunks/93519.js:1:1932
    at f (/app/.next/server/chunks/88615.js:4:74)
    at r (/app/.next/server/chunks/88615.js:1:5810)
    at /app/.next/server/chunks/20516.js:1:7781
    at Array.map (<anonymous>)
    at g (/app/.next/server/chunks/20516.js:1:7318)
    at async _ (/app/.next/server/app/(backend)/trpc/lambda/[trpc]/route.js:1:3799)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/server/base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/server/base-server.js:1581:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/server/base-server.js:1489:28)
    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/server/base-server.js:1913:24)
    at async NextNodeServer.renderToResponseImpl (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/server/base-server.js:1951:32)
    at async NextNodeServer.pipeImpl (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/server/base-server.js:917:25) {
  cause: undefined,
  code: 'UNAUTHORIZED'
}
[Chunking Error] n {
  name: 'NoChunkError',
  body: {
    detail: 'No chunk found in this file. it may due to current chunking method can not parse file accurately'
  }
}

**Comment by arvinxx** [comment]
说明这个 pdf 中目前没有文本块，识别不到内容，用 langchain 方案暂时不好解，得用 Unstructed.io 的方案
