### ISSUE TITLE
[Bug] Suddenly unable to configure language model

### ISSUE THREAD

**Issue by soanhee** [lobehub/lobehub#5096]
### 📦 Environment

Docker

### 📌 Version

1.36.37

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

最近兩天發現 Lobechat database 無法正常訪問 設定>語言模型，其他設定頁面以及功能(常用的)完全正常。
設定模型頁面會出現 404 錯誤。第一次發現是在1.36.0版本，更新1.36.35後解決了。

但今天問題再次出現，更新1.36.37後無法解決。

模型設置已啟用的服務包括 Openai, Ollama, Google, xAI, Qwen, Zhipu。
首次發現問題出現是在設置好 Google 後出現(不確定是否有關連)。

![Snipaste_2024-12-20_14-42-08](https://github.com/user-attachments/assets/ca152005-ca0c-4b2c-ac44-146c705479fd)

### 📷 Recurrence Steps

已嘗試透過域名外部訪問、部屬本機訪問、本地IP訪問。
設定>語言模型 404無法訪問，錯誤一樣。Docker多次重啟多次錯誤依然。

### 📝 Additional Information

```

TypeError: Failed to construct 'URL': Invalid URL                34373-955e326f9894062d.js:1 
    at m (8546-5448cf8ab74276aa.js:22:51811)
    at new w (8546-5448cf8ab74276aa.js:22:52307)
    at new d (94692-11f8fdd047766f11.js:1:39078)
    at 47177 (94692-11f8fdd047766f11.js:1:39141)
    at j (webpack-1edfae99f9f117d4.js:1:173)
    at 27714 (94692-11f8fdd047766f11.js:1:5648)
    at Function.j (webpack-1edfae99f9f117d4.js:1:173)
```

**Comment by arvinxx** [comment]
感觉是可能你配了一个不是 http 开头的 proxy url,检查下？后面我看下是哪里抛的错，修复下

**Comment by soanhee** [comment]
> 感觉是可能你配了一个不是 http 开头的 proxy url,检查下？后面我看下是哪里抛的错，修复下

感謝回覆，ollama 配了http開頭的proxy url, 問題似乎也是從配置這個proxy後才出現的

**Comment by arvinxx** [comment]
> ollama 配了http開頭的proxy url, 問題似乎也是從配置這個proxy後才出現的

把这个去掉

**Comment by soanhee** [comment]
> > ollama 配了http開頭的proxy url, 問題似乎也是從配置這個proxy後才出現的
> 
> 把这个去掉

現在lobechat無法透過ui進入模型設置頁面
(最近發現偶爾能進入，會先顯示沒有加載.css的畫面2秒，然後恢復，可以正常使用，但大部份時間都是404)
嘗試在.env中加入`OLLAMA_PROXY_URL=*`，依然無法進入模型設置頁面。
請問是否需要編輯數據庫>去掉?或者可以透過執行代碼修改?
感謝!
